create table if not exists public.solar_telemetry (
  id bigint generated by default as identity primary key,
  solar1_current numeric,
  solar2_current numeric,
  battery_current numeric,
  object_temperature numeric,
  battery_temperature numeric,
  mppt_temperature numeric,
  recorded_at timestamptz not null default timezone('utc', now())
);

create index if not exists solar_telemetry_recorded_at_idx on public.solar_telemetry (recorded_at desc);

create table if not exists public.solar_relay_states (
  relay text primary key check (relay in ('solar1', 'solar2', 'battery', 'bufik', 'fan12v', 'fan24v')),
  is_on boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now())
);

insert into public.solar_relay_states (relay) values
  ('solar1'), ('solar2'), ('battery'), ('bufik'), ('fan12v'), ('fan24v')
on conflict (relay) do nothing;

alter table public.solar_telemetry enable row level security;
alter table public.solar_relay_states enable row level security;

drop policy if exists "public_read_solar_telemetry" on public.solar_telemetry;
create policy "public_read_solar_telemetry" on public.solar_telemetry for select to anon, authenticated using (true);
drop policy if exists "public_insert_solar_telemetry" on public.solar_telemetry;
create policy "public_insert_solar_telemetry" on public.solar_telemetry for insert to anon, authenticated with check (true);
drop policy if exists "public_read_solar_relays" on public.solar_relay_states;
create policy "public_read_solar_relays" on public.solar_relay_states for select to anon, authenticated using (true);

create or replace function public.touch_solar_relay_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = timezone('utc', now()); return new; end; $$;
drop trigger if exists solar_relay_updated_at on public.solar_relay_states;
create trigger solar_relay_updated_at before update on public.solar_relay_states
for each row execute function public.touch_solar_relay_updated_at();
