create table if not exists public.solar_telemetry (
  id bigint generated by default as identity primary key,
  solar1_current numeric,
  solar2_current numeric,
  battery_current numeric,
  object_temperature numeric,
  battery_temperature numeric,
  mppt_temperature numeric,
  recorded_at timestamptz not null default timezone('utc', now())
);

alter table public.solar_telemetry add column if not exists solar1_voltage numeric;
alter table public.solar_telemetry add column if not exists solar2_voltage numeric;
alter table public.solar_telemetry add column if not exists battery_voltage numeric;
alter table public.solar_telemetry add column if not exists solar1_power numeric;
alter table public.solar_telemetry add column if not exists solar2_power numeric;
alter table public.solar_telemetry add column if not exists load_power numeric;
alter table public.solar_telemetry add column if not exists solar_energy_today_wh numeric;
alter table public.solar_telemetry add column if not exists load_energy_today_wh numeric;
alter table public.solar_telemetry add column if not exists rpi_cpu_temperature numeric;
alter table public.solar_telemetry add column if not exists object_humidity numeric;
alter table public.solar_telemetry add column if not exists outside_temperature numeric;
alter table public.solar_telemetry add column if not exists outside_pressure numeric;
alter table public.solar_telemetry add column if not exists mq9_raw numeric;
alter table public.solar_telemetry add column if not exists mq9_voltage numeric;
alter table public.solar_telemetry add column if not exists arduino_uptime_ms numeric;
alter table public.solar_telemetry add column if not exists battery_pressure numeric;
alter table public.solar_telemetry add column if not exists ina219_current numeric;
alter table public.solar_telemetry add column if not exists ina219_power numeric;
alter table public.solar_telemetry add column if not exists ina219_shunt_voltage_mv numeric;
alter table public.solar_telemetry add column if not exists acs1_raw numeric;
alter table public.solar_telemetry add column if not exists acs1_voltage numeric;
alter table public.solar_telemetry add column if not exists acs2_raw numeric;
alter table public.solar_telemetry add column if not exists acs2_voltage numeric;
alter table public.solar_telemetry add column if not exists acs3_raw numeric;
alter table public.solar_telemetry add column if not exists acs3_voltage numeric;
alter table public.solar_telemetry add column if not exists mq9_alarm boolean not null default false;
alter table public.solar_telemetry add column if not exists mq9_alarm_trigger_raw numeric;

create index if not exists solar_telemetry_recorded_at_idx on public.solar_telemetry (recorded_at desc);

create table if not exists public.solar_relay_states (
  relay text primary key check (relay in ('solar1', 'solar2', 'battery', 'bufik', 'fan12v', 'fan24v')),
  is_on boolean not null default false,
  updated_at timestamptz not null default timezone('utc', now())
);

insert into public.solar_relay_states (relay) values
  ('solar1'), ('solar2'), ('battery'), ('bufik'), ('fan12v'), ('fan24v')
on conflict (relay) do nothing;

alter table public.solar_telemetry enable row level security;
alter table public.solar_relay_states enable row level security;

drop policy if exists "public_read_solar_telemetry" on public.solar_telemetry;
create policy "public_read_solar_telemetry" on public.solar_telemetry for select to anon, authenticated using (true);
drop policy if exists "public_insert_solar_telemetry" on public.solar_telemetry;
create policy "public_insert_solar_telemetry" on public.solar_telemetry for insert to anon, authenticated with check (true);
drop policy if exists "public_read_solar_relays" on public.solar_relay_states;
create policy "public_read_solar_relays" on public.solar_relay_states for select to anon, authenticated using (true);
drop policy if exists "app_control_insert_solar_relays" on public.solar_relay_states;
create policy "app_control_insert_solar_relays" on public.solar_relay_states for insert to anon, authenticated with check (true);
drop policy if exists "app_control_update_solar_relays" on public.solar_relay_states;
create policy "app_control_update_solar_relays" on public.solar_relay_states for update to anon, authenticated using (true) with check (true);

create or replace function public.touch_solar_relay_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = timezone('utc', now()); return new; end; $$;
drop trigger if exists solar_relay_updated_at on public.solar_relay_states;
create trigger solar_relay_updated_at before update on public.solar_relay_states
for each row execute function public.touch_solar_relay_updated_at();
